# Generated by Django 5.0.4 on 2024-04-21 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compétence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desctription', models.CharField(blank=True, max_length=500, null=True)),
                ('icone', models.ImageField(upload_to='')),
                ('domaine', models.CharField(choices=[('AGRI', 'Agriculture Paysage'), ('ALIM', 'Alimentation'), ('ASSO', 'Associatif'), ('ANIM', 'Animaux'), ('ARCH', 'Architecture Decoration'), ('SECO', 'Secours Securite'), ('ARTI', 'Artisanat Design Mode'), ('BANQ', 'Banque Finance Assurance'), ('BIOL', 'Biologie Chimie'), ('BTPP', 'Btp'), ('CINE', 'Cinema'), ('JEUV', 'Jeux Video'), ('JEUS', 'Jeux Societe'), ('COME', 'Commerce Immobilier'), ('COMU', 'Communication Marketing'), ('SPEC', 'Culture Spectacle Patrimoine'), ('DROIT', 'Droit Justice'), ('LIVR', 'Edition Imprimerie'), ('LECT', 'Lecture'), ('ELEC', 'Electronique Robotique'), ('ENER', 'Energie'), ('FORM', 'Enseignement Formation'), ('ENVI', 'Environnement'), ('GEST', 'Gestion Entreprise'), ('COMPT', 'Comptabilite'), ('GERH', 'Gestion Rh'), ('REST', 'Restauration'), ('TOUR', 'Tourisme'), ('HUMA', 'Humanitaire'), ('INFO', 'Informatique'), ('LANG', 'Langues'), ('INDUS', 'Industrie'), ('MECA', 'Mecanique'), ('SANT', 'Sante'), ('MATH', 'Mathematiques'), ('PSYC', 'Sciences Humaines'), ('PHYS', 'Sciences Physique'), ('SOCI', 'Social'), ('SPOR', 'Sport'), ('TRANS', 'Transport'), ('VIEE', 'Vie')], max_length=5)),
                ('etat', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Defi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desctription', models.CharField(blank=True, max_length=500, null=True)),
                ('icone', models.ImageField(upload_to='')),
                ('etat', models.BooleanField(default=False)),
                ('niveau', models.IntegerField()),
                ('compétence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.compétence')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desctription', models.CharField(blank=True, max_length=500, null=True)),
                ('icone', models.ImageField(upload_to='')),
                ('complexite', models.IntegerField()),
                ('etat', models.CharField(choices=[('COM', 'Competences Acquises'), ('PLA', 'Mise En Place'), ('COU', 'En Cours'), ('FIN', 'Finalisation'), ('TER', 'Termine')], max_length=3)),
                ('precisions', models.CharField(blank=True, max_length=500, null=True)),
                ('constitué', models.ManyToManyField(to='application.compétence')),
            ],
        ),
    ]
